// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dexziyllvlpcjpzkksbs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRleHppeWxsdmxwY2pwemtrc2JzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3MDAwMTUsImV4cCI6MjA2MDI3NjAxNX0.HWJz4XClgrUhX8jjF3GbHHA4ujVz_bMjMYqzm9G4Srg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);